name: Run Selenium Tests Daily

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Setup ChromeDriver (matching Chrome)
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: latest
        env:
          CHROME_BIN: /usr/bin/google-chrome

      - name: Start virtual display (Xvfb)
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          export DISPLAY=:99

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Run Tests with Gradle
        run: ./gradlew clean test

      - name: Upload Test Reports (Extent Spark)
        uses: actions/upload-artifact@v4
        with:
          name: SparkReport
          path: build/reports/tests/spark.html
