name: Run Selenium Tests

on:
  schedule:
    - cron: '30 2 * * *'  # 08:00 AM IST daily (2:30 AM UTC)
  push:                   # triggers on any push
  workflow_dispatch:      # allows manual run

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Start virtual display (Xvfb)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -ac -screen 0 1920x1080x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Run Tests with Gradle
        run: ./gradlew clean test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Test Reports
          path: build/reports/tests/test